#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
numerical_solver.py
-------------------
Reads the *shared* manifest + forcing generated by:
    viscoelastic_vibration_datasets_generator.py

Then simulates each kernel using four solver variants:

  Integrators:
    • (I1) Semi-implicit Euler (robust for damped systems)
    • (I2) Velocity-Verlet (central-difference style)

  History evaluation for the Volterra damping term H(t) = ∫_0^t K(t-τ) u'(τ) dτ:
    • (H1) Prony internal states          (O(MN), constant memory, very fast)
    • (H2) FFT-based discrete convolution (O(N log N), exact convolution on grid)

→ Exports:
  ./results/kernels/<kernel_name>/
     ├─ kernel_params.csv
     ├─ kernel_curve.png
     ├─ semi_implicit__prony_state/
     │    ├─ timeseries.csv
     │    ├─ u_time.png
     │    └─ H_time.png
     ├─ semi_implicit__fft_conv/
     ├─ verlet__prony_state/
     └─ verlet__fft_conv/

All plots use matplotlib defaults (no seaborn, one chart per figure, no styles/colors).
"""

from __future__ import annotations
import json, math, pathlib
from typing import Callable
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from core_experiment import (
    KernelSpec,
    hash_array_sha256,
    generate_forcing,  # used ONLY if forcing.npy is missing (still checked via hash)
)

# -----------------------
# IO paths
# -----------------------
DS_ROOT     = pathlib.Path("./datasets/synthetic").resolve()
FORCING_NPY = DS_ROOT / "forcing.npy"
MANIFEST    = DS_ROOT / "manifest.json"

OUT_ROOT    = pathlib.Path("./results/kernels").resolve()

def ensure_dir(p: pathlib.Path) -> None:
    p.mkdir(parents=True, exist_ok=True)

# -----------------------
# Load manifest & forcing
# -----------------------
def load_manifest(path: pathlib.Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def load_forcing_or_regen(mani: dict) -> tuple[np.ndarray, float, int]:
    """
    Load forcing if available; otherwise regenerate from seed and verify SHA-256.

    Returns:
      f (np.ndarray), fs (float), N (int)
    """
    fs = float(mani["fs"])
    N  = int(mani["N"])

    if FORCING_NPY.exists():
        f = np.load(FORCING_NPY)
        # Verify size & hash
        if f.shape[0] != N:
            raise RuntimeError(f"forcing.npy length {f.shape[0]} != manifest N {N}")
        h = hash_array_sha256(f)
        if h != mani["forcing_sha256"]:
            raise RuntimeError("forcing.npy hash does not match manifest (data drift detected).")
        return f, fs, N

    # If missing, regenerate using saved seed_forcing & our *shared* generator
    seed_forcing = int(mani["seed_forcing"])
    rng = np.random.default_rng(seed_forcing)
    f = generate_forcing(N, fs, rng)
    h = hash_array_sha256(f)
    if h != mani["forcing_sha256"]:
        raise RuntimeError("Regenerated forcing hash does not match manifest (check core_experiment version).")
    # Save for convenience next time
    ensure_dir(DS_ROOT)
    np.save(FORCING_NPY, f)
    return f, fs, N

# -----------------------
# History evaluators
# -----------------------
def history_prony_states(v: np.ndarray, a_vec: np.ndarray, b_vec: np.ndarray, dt: float) -> np.ndarray:
    """
    Causal history H[n] via internal Prony states driven by v[n]:
      z_m[n] = e^{-b_m dt} z_m[n-1] + a_m dt v[n]
      H[n]   = Σ_m z_m[n]
    Complexity: O(MN), Memory: O(M)
    """
    z = np.zeros_like(a_vec, dtype=float)
    N = len(v)
    H = np.zeros(N, dtype=float)
    decay = np.exp(-b_vec * dt)
    for n in range(N):
        z *= decay
        z += a_vec * (dt * v[n])
        H[n] = z.sum()
    return H

def history_fft_conv(v: np.ndarray, a_vec: np.ndarray, b_vec: np.ndarray, dt: float) -> np.ndarray:
    """
    Discrete convolution H = dt * (K * v) via FFT:
      K[n] = Σ_m a_m e^{-b_m n dt}, n>=0
    Complexity: O(N log N), exact for the sampled K and v.
    """
    N = len(v)
    t = np.arange(N) * dt
    # K on the same grid
    K = np.exp(-np.outer(t, b_vec)) @ a_vec  # shape [N]
    # FFT-based linear convolution
    L = int(2 ** math.ceil(math.log2(2 * N - 1)))
    V = np.fft.rfft(v, n=L)
    Kpad = np.zeros(L, dtype=float); Kpad[:N] = K
    Khat = np.fft.rfft(Kpad, n=L)
    Y = V * Khat
    y = np.fft.irfft(Y, n=L)[:N]
    return dt * y

# -----------------------
# Integrators
# -----------------------
def simulate_semi_implicit(f: np.ndarray, omega: float, H_func: Callable[[np.ndarray], np.ndarray], dt: float) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Semi-implicit Euler for:
      u'' + ω^2 u + H = f,  where H depends on v=u'.

    Scheme:
      a[n] = f[n] - ω^2 u[n] - H[n]
      v[n+1] = v[n] + dt a[n]
      u[n+1] = u[n] + dt v[n+1]

    Predictor-corrector: iterate twice so H(v) and v are consistent.
    """
    N = len(f)
    u = np.zeros(N, dtype=float)
    v = np.zeros(N, dtype=float)
    H = np.zeros(N, dtype=float)

    for _ in range(2):  # 2 passes are usually enough for a stable fixed point
        a = f - (omega**2) * u - H
        v_new = np.empty_like(v)
        u_new = np.empty_like(u)
        v_new[0] = v[0] + dt * a[0]
        u_new[0] = u[0] + dt * v_new[0]
        for n in range(1, N):
            a[n] = f[n] - (omega**2) * u_new[n - 1] - H[n]
            v_new[n] = v_new[n - 1] + dt * a[n]
            u_new[n] = u_new[n - 1] + dt * v_new[n]
        v, u = v_new, u_new
        H = H_func(v)  # recompute history with latest velocity

    a = f - (omega**2) * u - H
    return u, v, a, H

def simulate_verlet(f: np.ndarray, omega: float, H_func: Callable[[np.ndarray], np.ndarray], dt: float) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Velocity-Verlet / central-difference style integrator with external history H(v).
    Two-pass approach:
      1) predictor with stale H (zeros),
      2) rebuild H from resulting v,
      3) corrector pass with the good H.
    """
    N = len(f)
    u = np.zeros(N, dtype=float)
    v = np.zeros(N, dtype=float)
    H = np.zeros(N, dtype=float)
    a = np.zeros(N, dtype=float)

    a[0] = f[0] - (omega**2) * u[0] - H[0]

    # Predictor pass
    for n in range(N - 1):
        u[n + 1] = u[n] + dt * v[n] + 0.5 * dt * dt * a[n]
        a_tilde = f[n] - (omega**2) * u[n] - H[n]
        v[n + 1] = v[n] + 0.5 * dt * (a[n] + a_tilde)
        H[n + 1] = H[n]  # placeholder
        a[n + 1] = f[n + 1] - (omega**2) * u[n + 1] - H[n + 1]

    # Rebuild H from v
    H = H_func(v)

    # Corrector pass
    a[0] = f[0] - (omega**2) * u[0] - H[0]
    for n in range(N - 1):
        u[n + 1] = u[n] + dt * v[n] + 0.5 * dt * dt * a[n]
        a_mid = f[n] - (omega**2) * u[n] - H[n]
        v[n + 1] = v[n] + 0.5 * dt * (a[n] + a_mid)
        a[n + 1] = f[n + 1] - (omega**2) * u[n + 1] - H[n + 1]

    return u, v, a, H

# -----------------------
# Run all kernels/methods
# -----------------------
def main() -> None:
    if not MANIFEST.exists():
        raise FileNotFoundError(
            f"Manifest not found at {MANIFEST}\n"
            "→ Run viscoelastic_vibration_datasets_generator.py first."
        )
    mani = load_manifest(MANIFEST)
    f, fs, N = load_forcing_or_regen(mani)
    dt = 1.0 / fs
    t = np.arange(N) * dt

    omega_list = [float(x) for x in mani["omega_list"]]
    kernels_json = mani["kernels"]

    # Simulate each kernel with 4 method combos
    for k_idx, (kobj, omega) in enumerate(zip(kernels_json, omega_list), start=1):
        name = kobj["name"]
        a_vec = np.array(kobj["a"], dtype=float)
        b_vec = np.array(kobj["b"], dtype=float)

        # Prepare output folders
        kdir = OUT_ROOT / name
        ensure_dir(kdir)

        # Save kernel params for reference (again here under results/)
        pd.DataFrame({"a": a_vec, "b": b_vec}).to_csv(kdir / "kernel_params.csv", index=False)

        # Save kernel curve (K(t) on a log grid)
        tK = np.geomspace(1e-4, 20.0, 2000)
        Kcurve = np.exp(-np.outer(tK, b_vec)) @ a_vec
        plt.figure()
        plt.loglog(tK, Kcurve)
        plt.xlabel("t (s)")
        plt.ylabel("K(t)")
        plt.title(f"Kernel {name}")
        plt.tight_layout()
        plt.savefig(kdir / "kernel_curve.png")
        plt.close()

        # History providers
        H_prony = lambda v: history_prony_states(v, a_vec, b_vec, dt)
        H_fft   = lambda v: history_fft_conv(v, a_vec, b_vec, dt)

        methods = [
            ("semi_implicit__prony_state", lambda: simulate_semi_implicit(f, omega, H_prony, dt)),
            ("semi_implicit__fft_conv",   lambda: simulate_semi_implicit(f, omega, H_fft, dt)),
            ("verlet__prony_state",       lambda: simulate_verlet(f, omega, H_prony, dt)),
            ("verlet__fft_conv",          lambda: simulate_verlet(f, omega, H_fft, dt)),
        ]

        for mname, runner in methods:
            mdir = kdir / mname
            ensure_dir(mdir)

            u, v, acc, H = runner()

            # Export full time series for later ML / analysis
            df = pd.DataFrame({
                "time": t,
                "forcing": f,
                "disp": u,
                "vel": v,
                "acc": acc,
                "hist": H,
            })
            df.to_csv(mdir / "timeseries.csv", index=False)

            # Displacement plot
            plt.figure()
            plt.plot(t, u)
            plt.xlabel("time (s)")
            plt.ylabel("displacement u(t)")
            plt.title(f"{name} · {mname}")
            plt.tight_layout()
            plt.savefig(mdir / "u_time.png")
            plt.close()

            # History term plot
            plt.figure()
            plt.plot(t, H)
            plt.xlabel("time (s)")
            plt.ylabel("history term H(t)")
            plt.title(f"{name} · {mname}")
            plt.tight_layout()
            plt.savefig(mdir / "H_time.png")
            plt.close()

    print(f"[OK] Results written to: {OUT_ROOT}")

if __name__ == "__main__":
    main()
